### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [tadeo14/Gestion-Hoteles-Front#35]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/user-attachments/assets/6ed706b3-9d6d-4bae-9809-3fe62ef0cfe8)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by tadeo14** [comment]
Ya se eliminaron
