### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [tadeo14/Gestion-Hoteles-Front#36]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar un logo que represente la pagina, al menos uno.
 
## Resultado actual

• No se encuentra ningun logo.

## Captura

![image](https://github.com/user-attachments/assets/814f3de9-10b2-4b95-8039-dd8e9596b7c5)
![image](https://github.com/user-attachments/assets/d5197b32-9a5b-4f23-a9f4-75a340ff0ca7)
![image](https://github.com/user-attachments/assets/5ae04d82-68f2-443c-a6d4-8aff308b346b)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by tadeo14** [comment]
![image](https://github.com/user-attachments/assets/e44a07d0-3715-4542-8089-ab86580808b5)
corregido
