### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by NicoGonzalez94** [tadeo14/Gestion-Hoteles-Front#37]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que no se permita colocar numeros ni signos en el nombre.
• Encontrar un limite de caracteres a colocar en numero de teléfono y en el mensaje de la consulta.

## Resultado actual

• Se permite colocar numeros y signos en el nombre.
• No hay un limite de caracteres a colocar en numero de teléfono y en el mensaje de la consulta.

## Captura

![image](https://github.com/user-attachments/assets/99b4dbbc-c7f3-43c4-a3f5-0788f81c789e)
![image](https://github.com/user-attachments/assets/fe607c14-d0aa-44ff-abe1-42ebea2bb592)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by tadeo14** [comment]
![image](https://github.com/user-attachments/assets/fb807e46-06f8-46f9-b9e5-227bfbe6487b)
corredigo
