### ISSUE TITLE
Form registro

### ISSUE THREAD

**Issue by NicoGonzalez94** [tadeo14/Gestion-Hoteles-Front#38]
## Proceso

1. Ingrese a la pagina.
2. Me quise registrar con un nuevo usuario.

## Resultado esperado

• Que no se permita colocar numero y signos en el nombre del usuario.

## Resultado actual

• Se permite colocar numeros y signos en el nombre del usuario.

## Captura

![image](https://github.com/user-attachments/assets/1a6947b9-4b7d-485c-9457-b931996abb0c)
![image](https://github.com/user-attachments/assets/38ebfa39-7162-45c7-b9b4-f7cc56a768e1)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by tadeo14** [comment]
![image](https://github.com/user-attachments/assets/ddcefb78-2002-495e-b951-f956c4a3c6d7)
corregido
